name: Run Tests

on:
  pull_request:
    branches: [master]

jobs:
  build:
    name: Develop-PR
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: add feed
        run: dotnet nuget add source https://nuget.pkg.github.com/acceliox/index.json --name github --store-password-in-clear-text --username acceliox --password ${{ secrets.VA_NUGET_FEED_TOKEN }}
      - name: Build Release
        run: dotnet build --configuration Release **/*.sln
      - name: Test
        run: dotnet test **/*.sln --verbosity normal
